import { Mail, Github, Linkedin, Twitter, ExternalLink } from "lucide-react";
import { useState } from "react";
import ProjectModal from "@/components/ProjectModal";

/**
 * Mellow Minimalist Academic Design Philosophy:
 * - Warm, soft color palette (warm beige, muted browns)
 * - Smooth transitions and animations (0.3s ease)
 * - Tabbed navigation for different sections
 * - Clean typography with generous whitespace
 * - Subtle hover effects with smooth transforms
 */

type Section = "home" | "projects" | "resume" | "publications" | "skills" | "blog" | "goals" | "connect";

interface Project {
  title: string;
  description: string;
  tags: string[];
  link?: string;
  year: string;
  details?: string;
}

interface BlogPost {
  title: string;
  excerpt: string;
  date: string;
  slug: string;
}

interface EducationItem {
  degree: string;
  institution: string;
  year: string;
  details: string;
}

interface Goal {
  title: string;
  description: string;
  status: "in-progress" | "planned" | "completed";
}

interface Publication {
  authors: string;
  title: string;
  journal: string;
  year: string;
  link?: string;
}

interface SkillCategory {
  category: string;
  skills: string[];
}

export default function Home() {
  const [activeSection, setActiveSection] = useState<Section>("home");
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const openProjectModal = (project: Project) => {
    setSelectedProject(project);
    setIsModalOpen(true);
  };

  const closeProjectModal = () => {
    setIsModalOpen(false);
    setSelectedProject(null);
  };

  const projects: Project[] = [
    {
      title: "Predictive Coding Model for Visual Illusions",
      description:
        "Master's Thesis Project at CERCO, Toulouse, France. Implementing Predictive Coding Framework into Machine Learning Models to understand perception of visual illusions by modulating priors in Predictive Coding Dynamics.",
      tags: ["PyTorch", "Machine Learning", "Neuroscience", "Computational Cognition"],
      year: "Ongoing",
      details: "Working with the Neuro AI Team under Andrea Alamia. Skills learned: Proficient at using PyTorch, creating datasets for machine learning, implementing computational models of cognition."
    },
    {
      title: "Community Detection Algorithm for Macaque Connectome",
      description:
        "Designed a community detection algorithm for Macaque connectome data. Achieved high accuracy in networks generated by the stochastic block model and successfully assigned communities to the macaque connectome network.",
      tags: ["Network Science", "Neuroscience", "MATLAB", "Graph Theory"],
      year: "May-June 2024",
      details: "Summer Student at Department of Computational Biology, The Institute of Mathematical Sciences, Chennai. Supervisor: Dr Sitabhra Sinha. Skills learned: Implementation of graph theory concepts into network science and their relation to neuroscience."
    },
    {
      title: "Autoencoder Model for Genome Sequence Clustering",
      description:
        "Building auto encoders whose latent representations will be used to cluster different genomic sequences for further inference of their role in biochemical activity. Extension of Cisdiversity using a machine learning approach.",
      tags: ["PyTorch", "Machine Learning", "Genomics", "Autoencoders"],
      year: "Dec 2024-Apr 2025",
      details: "Semester Project at IISER Pune with Prof. Leelavati Narlikar. Skills learned: Developing Autoencoder Models with PyTorch and data processing of genome sequence data."
    },
    {
      title: "MAGNETIC: Gene Network Web Server",
      description:
        "Developed backend pipelines and interactive D3.js visualizations for large-scale genetic networks. Built a full-stack web server to explore motif-distribution-based gene correlations. Published in Nucleic Acids Research, 2025.",
      tags: ["Web Development", "D3.js", "Genomics", "Backend", "Full-Stack"],
      link: "https://academic.oup.com/nar/article/53/W1/W376/7918622",
      year: "May 2023-May 2024",
      details: "Publication Project at IISER Pune with Prof. MS Madhusudhan. Co-authored peer-reviewed publication in Nucleic Acids Research."
    },
    {
      title: "Behavioral Assays in Chemotherapy-Induced Neuropathy",
      description:
        "Conducted in vivo mouse behavioral studies to assess neuropathy effects of cancer drugs. Contributed to experiments linking axonal degradation and sensory behavior.",
      tags: ["Molecular Biology", "Neuroscience", "In Vivo Studies"],
      year: "July-Nov 2024",
      details: "Semester Project at IISER Pune with Prof. Aurnab Ghose in the Department of Biology."
    },
  ];

  const education: EducationItem[] = [
    {
      degree: "Bachelors and Masters in Science Integrated",
      institution: "Indian Institute of Science Education and Research (IISER), Pune, India",
      year: "2021–2026 (May)",
      details:
        "Major: Interdisciplinary (Biology and Data Science)",
    },
    {
      degree: "Senior Secondary",
      institution: "Geeta Mata College, Pune, India",
      year: "2018–2020",
      details: "Completed senior secondary education",
    },
    {
      degree: "Matriculation",
      institution: "Wisdom World School, Pune, India",
      year: "2018",
      details: "Completed secondary education",
    },
  ];

  const blogPosts: BlogPost[] = [
    {
      title: "Understanding Quantum Entanglement",
      excerpt:
        "A deep dive into the phenomenon of quantum entanglement and its implications for quantum computing.",
      date: "November 15, 2024",
      slug: "quantum-entanglement",
    },
    {
      title: "My Journey into Scientific Research",
      excerpt:
        "Reflections on starting my research career and lessons learned from my first major project.",
      date: "October 28, 2024",
      slug: "research-journey",
    },
    {
      title: "Best Practices for Data Visualization",
      excerpt:
        "A guide to creating clear, effective visualizations for scientific data.",
      date: "October 5, 2024",
      slug: "data-visualization",
    },
  ];

  const goals: Goal[] = [
    {
      title: "Publish in a Peer-Reviewed Journal",
      description: "Submit and publish research on quantum algorithms.",
      status: "in-progress",
    },
    {
      title: "Start a Youtube Channel",
      description: "I'm a huge fan of story telling and I wish to document some of the adventures of my life through vlogging.",
      status: "in-progress",
    },
    {
      title: "Contribute to Open Source",
      description: "Make meaningful contributions to scientific computing libraries.",
      status: "planned",
    },
    {
      title: "Learn Rust for Systems Programming",
      description: "Master Rust for high-performance computing applications.",
      status: "planned",
    },
  ];

  const publications: Publication[] = [
    {
      authors: "Atreyi Chakraborty, Saksham Srimali, Rohan Topno, Ajinkya Ranshur, Mallur Srivatsan Madhusudhan",
      title: "MAGNETIC: a web server to fetch gene network based on motif distribution in promoters",
      journal: "Nucleic Acids Research, Volume 53, Issue W1, 7 July 2025, Pages W376–W382",
      year: "2025",
      link: "https://academic.oup.com/nar/article/53/W1/W376/7918622"
    }
  ];

  const skillCategories: SkillCategory[] = [
    {
      category: "Programming Languages",
      skills: [
        "Python (Proficient) - Machine learning (scikit-learn, PyTorch), data analysis (pandas, NumPy), visualization (matplotlib, seaborn)",
        "R - Statistical modeling and exploratory data analysis",
        "C++ - Computational models and simulations",
        "MATLAB - Research projects and modeling"
      ]
    },
    {
      category: "Machine Learning & Computational Neuroscience",
      skills: [
        "Deep learning model development and training for neural network activity analysis",
        "GPU computing (CUDA, PyTorch) for large-scale simulations",
        "Predictive coding frameworks and computational models of cognition"
      ]
    },
    {
      category: "Tools & Practices",
      skills: [
        "Version control (Git/GitHub) - Collaborative coding and project management",
        "Linux / HPC clusters - Job scheduling and ML workloads on GPUs",
        "Web Development - Backend pipelines, D3.js visualizations, full-stack development"
      ]
    },
    {
      category: "Data Science & Statistics",
      skills: [
        "Statistical inference and Bayesian methods",
        "Graph theory and network science",
        "Image processing and NLP using neural networks"
      ]
    }
  ];

  const socialLinks = [
    {
      name: "Email",
      icon: Mail,
      href: "mailto:ranshur.ajinkya.res@gmail.com",
      label: "ranshur.ajinkya.res@gmail.com",
    },
    {
      name: "GitHub",
      icon: Github,
      href: "https://github.com/AjinkyaRanshur",
      label: "github.com/AjinkyaRanshur",
    },
    {
      name: "LinkedIn",
      icon: Linkedin,
      href: "https://linkedin.com/in/ajinkya-ranshur",
      label: "linkedin.com/in/ajinkya-ranshur",
    },
    {
      name: "Twitter",
      icon: Twitter,
      href: "https://twitter.com/Ajinkya_2107",
      label: "@Ajinkya_2107",
    },
  ];

  const navItems: { id: Section; label: string }[] = [
    { id: "home", label: "Home" },
    { id: "projects", label: "Projects" },
    { id: "resume", label: "Resume" },
    { id: "publications", label: "Publications" },
    { id: "skills", label: "Skills" },
    { id: "goals", label: "Goals" },
    { id: "connect", label: "Connect" },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header with Navigation */}
      <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-sm border-b border-border">
        <div className="container max-w-4xl">
          <div className="flex justify-between items-center py-4 mb-0">
            <h1 className="text-2xl font-bold">Ajinkya Ranshur</h1>
          </div>
          {/* Navigation Tabs */}
          <nav className="nav-tabs">
            {navItems.map((item) => (
              <button
                key={item.id}
                onClick={() => setActiveSection(item.id)}
                className={`nav-tab ${activeSection === item.id ? "active" : ""}`}
              >
                {item.label}
              </button>
            ))}
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="container max-w-4xl py-12 md:py-16">
        {/* Home Section */}
        {activeSection === "home" && (
          <section className="content-section">
            <div className="mb-12">
              <p className="text-lg text-foreground/80 mb-4">
                Master's Student in Neuroscience | Machine Learning Enthusiast | Computational Biology Researcher
              </p>
              <p className="text-base text-foreground/70 max-w-2xl leading-relaxed">
                I'm interested in developing mathematical models that mimic (some aspects of the) processes inside the brain,
                for which I'm currently using machine learning as a tool. My work spans neuroscience, computational biology,
                and genomics, with a focus on predictive coding models and neural network dynamics.
              </p>
              <p className="text-base text-foreground/70 max-w-2xl leading-relaxed mt-4">
                In the near future I wish to build more mathematically inclined models with the help of non-linear dynamics
                and probability theory. Currently completing my integrated BS-MS at IISER Pune with a major in Interdisciplinary
                studies (Biology and Data Science).
              </p>
            </div>
          </section>
        )}

        {/* Projects Section */}
        {activeSection === "projects" && (
          <section className="content-section">
            <h2 className="text-3xl font-bold mb-8">Scientific Projects</h2>
            <div className="space-y-8">
              {projects.map((project, idx) => (
                <div
                  key={idx}
                  className="project-item cursor-pointer"
                  onClick={() => openProjectModal(project)}
                >
                  <div className="flex justify-between items-start mb-2">
                    <h3 className="text-xl font-bold">{project.title}</h3>
                    <span className="text-sm text-foreground/60">
                      {project.year}
                    </span>
                  </div>
                  <p className="text-foreground/80 mb-3">{project.description}</p>
                  <div className="flex flex-wrap gap-2 mb-3">
                    {project.tags.map((tag, tagIdx) => (
                      <span key={tagIdx} className="tag">
                        {tag}
                      </span>
                    ))}
                  </div>
                  <div className="text-accent text-sm font-medium hover:underline">
                    Click to view details →
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Resume Section */}
        {activeSection === "resume" && (
          <section className="content-section">
            <h2 className="text-3xl font-bold mb-8">Education & Experience</h2>
            <div className="space-y-8">
              {education.map((edu, idx) => (
                <div key={idx} className="project-item">
                  <h3 className="text-xl font-bold mb-1">{edu.degree}</h3>
                  <p className="text-foreground/70 mb-2">{edu.institution}</p>
                  <p className="text-sm text-foreground/60 mb-3">{edu.year}</p>
                  <p className="text-foreground/80">{edu.details}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Publications Section */}
        {activeSection === "publications" && (
          <section className="content-section">
            <h2 className="text-3xl font-bold mb-8">Publications</h2>
            <div className="space-y-6">
              {publications.map((pub, idx) => (
                <div key={idx} className="project-item">
                  <h3 className="text-lg font-bold mb-2">{pub.title}</h3>
                  <p className="text-foreground/70 mb-2">{pub.authors}</p>
                  <p className="text-foreground/80 mb-3">{pub.journal}</p>
                  {pub.link && (
                    <a
                      href={pub.link}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-accent hover:text-accent/80 transition-colors text-sm font-medium inline-flex items-center gap-1"
                    >
                      View Publication <ExternalLink size={14} />
                    </a>
                  )}
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Skills Section */}
        {activeSection === "skills" && (
          <section className="content-section">
            <h2 className="text-3xl font-bold mb-8">Skills & Expertise</h2>
            <div className="space-y-8">
              {skillCategories.map((category, idx) => (
                <div key={idx} className="project-item">
                  <h3 className="text-xl font-bold mb-4">{category.category}</h3>
                  <ul className="space-y-2">
                    {category.skills.map((skill, skillIdx) => (
                      <li key={skillIdx} className="text-foreground/80 pl-4 relative before:content-['•'] before:absolute before:left-0 before:text-accent">
                        {skill}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Blog Section */}
        {activeSection === "blog" && (
          <section className="content-section">
            <h2 className="text-3xl font-bold mb-8">Blog</h2>
            <div className="space-y-6">
              {blogPosts.map((post, idx) => (
                <div key={idx} className="blog-preview">
                  <a href={`/blog/${post.slug}`} className="block group">
                    <h3 className="text-lg font-bold mb-2 group-hover:text-accent transition-colors">
                      {post.title}
                    </h3>
                  </a>
                  <p className="text-foreground/80 mb-3">{post.excerpt}</p>
                  <p className="text-sm text-foreground/60">{post.date}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Goals Section */}
        {activeSection === "goals" && (
          <section className="content-section">
            <h2 className="text-3xl font-bold mb-8">Life Goals</h2>
            <div className="space-y-6">
              {goals.map((goal, idx) => (
                <div key={idx} className="card">
                  <div className="flex justify-between items-start mb-2">
                    <h3 className="text-lg font-bold">{goal.title}</h3>
                    <span
                      className={`text-xs px-2 py-1 transition-all ${
                        goal.status === "completed"
                          ? "bg-green-100 text-green-800"
                          : goal.status === "in-progress"
                            ? "bg-blue-100 text-blue-800"
                            : "bg-gray-100 text-gray-800"
                      }`}
                    >
                      {goal.status === "in-progress"
                        ? "In Progress"
                        : goal.status === "completed"
                          ? "Completed"
                          : "Planned"}
                    </span>
                  </div>
                  <p className="text-foreground/80">{goal.description}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Connect Section */}
        {activeSection === "connect" && (
          <section className="content-section">
            <h2 className="text-3xl font-bold mb-8">Get In Touch</h2>
            <p className="text-foreground/80 mb-8 max-w-2xl">
              Feel free to reach out through any of these channels. I'm always
              interested in discussing science, technology, and new ideas.
            </p>
            <div className="space-y-4">
              {socialLinks.map((link, idx) => {
                const Icon = link.icon;
                return (
                  <a
                    key={idx}
                    href={link.href}
                    className="flex items-center gap-3 p-4 hover:bg-secondary/30 transition-colors duration-300 group"
                  >
                    <Icon
                      size={20}
                      className="text-accent group-hover:text-accent/80 transition-colors"
                    />
                    <span className="text-foreground/80 group-hover:text-accent transition-colors">
                      {link.label}
                    </span>
                  </a>
                );
              })}
            </div>
          </section>
        )}
      </main>

      {/* Project Modal */}
      <ProjectModal
        isOpen={isModalOpen}
        onClose={closeProjectModal}
        project={selectedProject}
      />

      {/* Footer */}
      <footer className="border-t border-border py-8 mt-16">
        <div className="container max-w-4xl">
          <p className="text-sm text-foreground/60 text-center">
            © 2026 Ajinkya Ranshur. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}

